# Pre-commit hooks for automated code quality enforcement
# See https://pre-commit.com for more information

repos:
  # Black - The uncompromising Python code formatter
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.9
        args: ['--line-length=88']

  # Ruff - An extremely fast Python linter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  # Mypy - Static type checker for Python
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic>=2.10
          - sqlalchemy>=2.0
          - types-requests
        args: [--ignore-missing-imports, --explicit-package-bases]
        exclude: ^(tests/|docs/)

  # Pre-commit built-in hooks for basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-json
      - id: check-toml
      - id: detect-private-key
