"""Initial simplified schema (10 fields, no token tracking)

Revision ID: e00ce3553a95
Revises: 
Create Date: 2025-10-16 14:06:18.617745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e00ce3553a95'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sha256_hex', sa.String(length=64), nullable=False, comment='SHA-256 hash in hexadecimal format for deduplication'),
    sa.Column('original_filename', sa.String(length=512), nullable=False, comment='Original PDF filename from inbox'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='UTC timestamp when document was first discovered'),
    sa.Column('processed_at', sa.DateTime(), nullable=True, comment='UTC timestamp when processing completed successfully'),
    sa.Column('source_file_id', sa.String(length=64), nullable=True, comment='OpenAI file ID from Files API upload'),
    sa.Column('vector_store_file_id', sa.String(length=64), nullable=True, comment='OpenAI vector store file ID for cross-document search (Workstream 4)'),
    sa.Column('metadata_json', sa.JSON(), nullable=True, comment='Full structured output from OpenAI Responses API'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='Processing status: pending|processing|completed|failed|vector_upload_failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if status is failed'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_sha256_hex'), 'documents', ['sha256_hex'], unique=True)
    op.create_index(op.f('ix_documents_source_file_id'), 'documents', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_vector_store_file_id'), 'documents', ['vector_store_file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_vector_store_file_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_source_file_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_sha256_hex'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
